1461881473409	Sync.Service	INFO	Loading Weave 1.47.0
1461881473411	Sync.Engine.Clients	DEBUG	Engine initialized
1461881473412	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1461881473420	Sync.Engine.Bookmarks	DEBUG	Engine initialized
1461881473422	Sync.Engine.Forms	DEBUG	Engine initialized
1461881473426	Sync.Engine.History	DEBUG	Engine initialized
1461881473431	Sync.Engine.Passwords	DEBUG	Engine initialized
1461881473435	Sync.Engine.Prefs	DEBUG	Engine initialized
1461881473439	Sync.Engine.Tabs	DEBUG	Engine initialized
1461881473439	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1461881473442	Sync.Engine.Addons	DEBUG	Engine initialized
1461881473443	Sync.Service	INFO	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
1461881473446	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1461881473446	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1461881473447	Sync.Service	DEBUG	Caching URLs under storage user base: https://sync-212-us-west-2.sync.services.mozilla.com/1.5/21753972/
1461881473447	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1461881473447	Sync.AddonsReconciler	INFO	Registering as Add-on Manager listener.
1461881473447	Sync.AddonsReconciler	DEBUG	Adding change listener.
1461881473447	Sync.Tracker.History	INFO	Adding Places observer.
1461881473471	browserwindow.syncui	DEBUG	observed: weave:service:ready
1461881473473	browserwindow.syncui	DEBUG	observed: weave:service:ready
1461881473474	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1461881473476	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1461881473477	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1461881473479	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1461881473479	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1461881478474	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1461881478475	Sync.Service	DEBUG	User-Agent: Firefox/45.0.2 FxSync/1.47.0.20160420132730.
1461881478475	Sync.Service	INFO	Starting sync at 2016-04-29 07:11:18
1461881478475	Sync.Service	DEBUG	In sync: should login.
1461881478475	browserwindow.syncui	DEBUG	observed: weave:service:login:start
1461881478475	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1461881478475	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1461881478475	Sync.Service	INFO	Logging in the user.
1461881478477	Sync.BrowserIDManager	INFO	Waiting for user to be verified.
1461881478477	FirefoxAccounts	DEBUG	already verified
1461881478478	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1461881478478	Sync.BrowserIDManager	INFO	Starting fetch for key bundle.
1461881478479	FirefoxAccounts	DEBUG	already verified
1461881478479	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1461881478479	FirefoxAccounts	DEBUG	enter getAssertion()
1461881478485	browserwindow.syncui	DEBUG	_loginFailed has sync state=success.login
1461881478486	FirefoxAccounts	DEBUG	got keyPair
1461881478486	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1461881486696	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms.
1461881503856	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881519898	Sync.Tracker.Forms	DEBUG	Saving changed IDs to forms
1461881520289	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881526418	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881533556	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881542751	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881549529	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881552093	Sync.Tracker.History	DEBUG	Saving changed IDs to history
1461881568826	Hawk	WARN	hawk request error: [Exception... "NS_ERROR_ABORT"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465"  data: no] Stack trace: onStopRequest()@resource://services-common/rest.js:465 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568826	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < _onComplete()@resource://services-common/hawkclient.js:218 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568827	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 659"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:659 < _onComplete()@resource://services-common/hawkclient.js:221 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568827	Hawk	DEBUG	(Response) /certificate/sign: code: null - Status text: null
1461881568827	Sync.RESTResponse	TRACE	Processing response headers.
1461881568828	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:315 < _onComplete()@resource://services-common/hawkclient.js:228 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568828	Sync.RESTResponse	TRACE	Processing response headers.
1461881568828	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:315 < _onComplete()@resource://services-common/hawkclient.js:229 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568828	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 659"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:659 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:121 < _onComplete()@resource://services-common/hawkclient.js:234 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568829	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:122 < _onComplete()@resource://services-common/hawkclient.js:234 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568829	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:123 < _onComplete()@resource://services-common/hawkclient.js:234 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568829	Sync.RESTResponse	TRACE	Processing response headers.
1461881568830	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:128 < _onComplete()@resource://services-common/hawkclient.js:234 < onComplete()@resource://services-common/hawkclient.js:275 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:156 < onNotify()@resource://gre/modules/services-sync/service.js:1009 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1031 < sync/<()@resource://gre/modules/services-sync/service.js:1283 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1279
1461881568830	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"error":{},"errorString":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1461881568830	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"error":{},"errorString":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1461881568830	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: {"error":{},"errorString":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1461881568831	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1461881568831	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1461881568831	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: {"error":{},"errorString":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1461881569249	Hawk	DEBUG	(Response) /account/status?uid=ccf072c195474cfc862eeb993553043e: code: 200 - Status text: OK
1461881569249	Sync.RESTResponse	TRACE	Processing response headers.
1461881569249	Hawk	DEBUG	Clock offset vs https://api.accounts.firefox.com/v1: -32401249
1461881569250	Sync.BrowserIDManager	ERROR	Could not authenticate: {"error":{},"errorString":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1461881569250	browserwindow.syncui	DEBUG	observed: weave:service:login:error
1461881569250	browserwindow.syncui	DEBUG	onLoginError: login=error.login.reason.network, sync=success.sync
1461881569251	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1461881569251	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms.
1461881569252	Sync.ErrorHandler	ERROR	Sync encountered a login error
